version: "3"
services:
  ripper:
    #build: ./
    image: docker-spotify-ripper-image
    volumes:
      - ~/Music/Spotify:/data
      - ./spotify_appkey.key:/root/.spotify-ripper/spotify_appkey.key
      - ./config.ini:/root/.spotify-ripper/config.ini
