version: "3"
services:
  ripper:
    build: ./
    volumes:
      - ~/Music/Spotify:/data
      - ./spotify_appkey.key:/root/.spotify-ripper/spotify_appkey.key
      - ./config.ini:/root/.spotify-ripper/config.ini
